version: "3"

services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ENV: staging
      AUTH_DOMAIN: dev-26i1fsf2m1n6hqk1.us.auth0.com
      AUTH_AUDIENCE: https://dev-26i1fsf2m1n6hqk1.us.auth0.com/api/v2/
    container_name: gateway
    volumes:
      - ./config:/config
    working_dir: /config
    ports:
      - "8180:8080"
      - "8181:8081"
    networks:
      - backend-network

networks:
  backend-network:
    name: custom_network
