---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: api-gateway
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  secretRef:
    name: backend-api-gateway-secret
  url: https://git@github.com/SolomonAIEngineering/backend-api-gateway
