---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: api-gateway
  namespace: flux-system
spec:
  interval: 30m0s
  path: ./kustomize/overlays/staging
  prune: true
  retryInterval: 2m0s
  sourceRef:
    kind: GitRepository
    name: api-gateway
  timeout: 3m0s
  wait: true
