apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patches:
- path: patch-configmap.yaml
- path: patch-deployment.yaml
- path: patch-pod.yaml
- path: patch-service.yaml
- path: patch-serviceaccount.yaml
- path: patch-serviceprofile.yaml
