---
# Source: api-gateway/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    helm.sh/chart: api-gateway-1.0.1
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: api-gateway
    app.kubernetes.io/version: "3.1.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
      app.kubernetes.io/instance: api-gateway
  template:
    metadata:
      annotations:
        timestamp: "20231110153251"
        prometheus.io/path: "__stats"
        prometheus.io/port: "8081"
        prometheus.io/scrape: "true"
      labels:
        app.kubernetes.io/name: api-gateway
        app.kubernetes.io/instance: api-gateway
    spec:
      volumes:
        - name: config
          configMap:
            name: api-gateway-configmap
      serviceAccountName: api-gateway
      securityContext:
        {}
      containers:
        - name: api-gateway
          securityContext:
            {}
          image: "feelguuds/api-gateway:3.1.0"
          imagePullPolicy: IfNotPresent
          command: [ "/usr/bin/krakend" ]
          args: [ "run", "-d", "-c", "/etc/krakend/krakend.json", "-p", "8080" ]
          env:
          - name: KRAKEND_PORT
            value: "8080"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: metrics
              containerPort: 8081
              protocol: TCP
          resources:
            limits:
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 64Mi

