---
# Source: api-gateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    helm.sh/chart: api-gateway-1.0.1
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: api-gateway
    app.kubernetes.io/version: "2.4.1"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: http
      nodePort: 32093
      protocol: TCP
      name: http
    - port: 8081
      targetPort: http
      protocol: TCP
      name: metrics
      nodePort: 32094
  selector:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/instance: api-gateway

