name: release artifacts

on:
  push:
    tags:
      - '*'

permissions:
  contents: write
  id-token: write
  packages: write

env:
  HELM_CHART_PATH: charts/api-gateway
  DOCKER_IMAGE: docker.io/feelguuds/api-gateway
  GHCR_REGISTRY: ghcr.io/solomonaiengineering
  K8S_VERSION: '1.28.0'
  HELM_VERSION: '3.8.1'
  GO_VERSION: '1.21.x'

jobs:
  publish-artifacts:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            release_suffix: ubuntu
          - os: macos-latest
            release_suffix: mac
          - os: windows-latest
            release_suffix: windows
        platform: [linux/amd64, linux/arm64]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Release and Branch Info
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV

      - name: Setup Tools
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Setup Helm
        uses: ./.github/actions/helm
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Login to Docker Registries
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Artifact Information
        run: |
          VERSION=sha-${GITHUB_SHA::8}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF/refs\/tags\//}
          fi
          HELM_VERSION=$(grep 'version:' ${{ env.HELM_CHART_PATH }}/Chart.yaml | tail -n1 | awk '{ print $2}')
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "REVISION=$GITHUB_SHA" >> $GITHUB_OUTPUT
          echo "HELM_VERSION=$HELM_VERSION" >> $GITHUB_OUTPUT

      - name: Validate Service Helm Chart
        uses: elifesciences/helm-validator-action@master
        with:
          chartPath: ${{ env.HELM_CHART_PATH }}
          kubernetesVersion: ${{ env.K8S_VERSION }}

      - name: Publish Helm Chart
        uses: stefanprodan/helm-gh-pages@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          charts_dir: charts
          charts_url: https://charts.melodiy.io
          owner: SolomonAIEngineering
          repository: backend-api-gateway
          branch: gh-pages

      - name: Publish Artifacts to GHCR
        run: |
          helm package ${{ env.HELM_CHART_PATH }}
          helm push api-gateway-${{ steps.prep.outputs.HELM_VERSION }}.tgz oci://${{ env.GHCR_REGISTRY }}/charts
          rm api-gateway-${{ steps.prep.outputs.HELM_VERSION }}.tgz
        continue-on-error: true

      - name: Generate Docker Image Metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: type=raw,value=${{ steps.prep.outputs.VERSION }}

      - name: Publish Multi-Arch Docker Image
        uses: docker/build-push-action@v3
        with:
          sbom: true
          provenance: true
          push: ${{ github.event_name != 'pull_request' }}
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: ${{ matrix.platform }}
          build-args: REVISION=${{ steps.prep.outputs.REVISION }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Debug Failure
        if: failure()
        run: kubectl logs -l app=api-gateway || true
