name: Main Branch CI/CD Release

on:
  push:
    branches:
      - main

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
      - name: Setup kubeconform
        uses: ./.github/actions/kubeconform
      - name: Execute And Release A Minor Version Of The Service
        run: |
          git config --global user.email "yoanyombapro@gmail.com"
          git config --global user.name "Yoan Yomba"
          make release-major-version