name: Main Branch CI/CD Release

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write
  
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && startsWith(github.head_ref, 'staging')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 10
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install
      - name: Setup kubeconform
        uses: ./.github/actions/kubeconform
      - name: Execute And Release A Minor Version Of The Service
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "yoanyombapro@gmail.com"
          git config --global user.name "Yoan Yomba"
          make release