name: release artifacts to staging environment

# release artifacts
on:
  push:
    branches: main

permissions:
  contents: write
  id-token: write
  packages: write

env:
  HELM_CHART_PATH: charts/api-gateway
  DOCKER_IMAGE: docker.io/solomonai/api-gateway
  GHCR_REGISTRY: ghcr.io/solomonaiengineering
  K8S_VERSION: "1.29.0"
  HELM_VERSION: "3.8.1"
  GO_VERSION: "1.21.x"
  REPOSITORY: "backend-api-gateway"
  OWNER: "SolomonAiEngineering"
  CHARTS_DIRECTORY: "charts"
  CHARTS_URL: "https://charts.melodiy.io"
  HELM_PUBLISH_BRANCH: "gh-pages"
  EKS_CLUSTER_NAME: solomonai-engineering-staging-cluster
  ECR_REPOSITORY: api-gateway

jobs:
  publish-artifacts:
    strategy:
      matrix:
        os: [ubuntu-latest]
        include:
          - os: ubuntu-latest
            release_suffix: ubuntu
        platform: [linux/amd64, linux/arm64, linux/arm64/v8]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        working-directory: .
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Release and Branch Info
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "GIT_BRANCH=${GITHUB_BASE_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_ENV

      - name: Setup Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
      - name: Set short git commit SHA
        id: commit
        uses: prompt/actions-commit-hash@v2
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Setup Helm
        uses: ./.github/actions/helm
        with:
          version: ${{ env.HELM_VERSION }}

      - name: Login to Docker Registries
        uses: docker/login-action@v2
        with:
          registry: ${{ env.GHCR_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare Artifact Information
        run: |
          VERSION=sha-${GITHUB_SHA::8}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF/refs\/tags\//}
          fi
          HELM_VERSION=$(grep 'version:' ${{ env.HELM_CHART_PATH }}/Chart.yaml | tail -n1 | awk '{ print $2}')
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "REVISION=$GITHUB_SHA" >> $GITHUB_OUTPUT
          echo "HELM_VERSION=$HELM_VERSION" >> $GITHUB_OUTPUT

      - name: Validate Service Helm Chart
        uses: elifesciences/helm-validator-action@master
        with:
          chartPath: ${{ env.HELM_CHART_PATH }}
          kubernetesVersion: ${{ env.K8S_VERSION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      - name: Prepare Artifact Information
        run: |
          VERSION=sha-${GITHUB_SHA::8}
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF/refs\/tags\//}
          fi
          HELM_VERSION=$(grep 'version:' ${{ env.HELM_CHART_PATH }}/Chart.yaml | tail -n1 | awk '{ print $2}')
          echo "BUILD_DATE=$(date -u +'%Y-%m-%dT%H:%M:%SZ')" >> $GITHUB_OUTPUT
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "REVISION=$GITHUB_SHA" >> $GITHUB_OUTPUT
          echo "HELM_VERSION=$HELM_VERSION" >> $GITHUB_OUTPUT
      - name: Validate Service Helm Chart
        run: make lint
      - name: Generate Docker Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.DOCKER_IMAGE }}
          tags: type=raw,value=${{ steps.prep.outputs.VERSION }}
      - name: Build and Push Docker Image
        run: docker build --tag ${{ env.ECR_REPOSITORY }}:staging_${{ steps.commit.outputs.short }} --tag ${{ env.ECR_REPOSITORY }}:staging ./Dockerfile.staging
      - name: Push to ECR
        id: ecr
        uses: jwalton/gh-ecr-push@v1
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          image: ${{ env.ECR_REPOSITORY }}:staging_${{ steps.commit.outputs.short }}
      - name: Debug Failure
        if: failure()
        run: kubectl logs -l app=api-gateway || true
  deploy:
    needs: [publish-artifacts]
    runs-on: ubuntu-latest
    env:
      working-directory: .
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Update SHA
        run: echo $GITHUB_SHA > $GITHUB_WORKSPACE/sha/_meta
      - name: Set short git commit SHA
        id: commit
        uses: prompt/actions-commit-hash@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ env.EKS_CLUSTER_NAME}} --region ${{ secrets.AWS_REGION }}
      - name: Deploy to EKS
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ steps.commit.outputs.short }}
        run: |
          helm upgrade --install api-gateway ./charts/api-gateway --values ./charts/api-gateway/values.staging.yaml --set image.tag=staging_${{ steps.commit.outputs.short }} -n platform
